# Setup
title:               雜物儲存室
tagline:             'Coding Blog'
description:         ''
url:                 https://davidyujia.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              David
  url:               https://github.com/davidyujia
  email:             davidyujia@gmail.com


# Custom vars
version:             1.1.0
google_analytics_id: UA-122167031-1

# Comments
disqus-shortname: davidyujia

exclude:
  - README.md
  - LICENSE.md

# Gems
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
