# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            MyBlog
tagline:          'Simple Blog'
description:      'abc'
url:              https://coolwhispers.github.io
baseurl:          /

author:
  name:           'U+'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/coolwhispers
