# Setup
title:               雜物儲存室
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              David
  url:               https://github.com/davidyujia
  email:             davidyujia@gmail.com


# Custom vars
version:             1.1.0
google_analytics_id: UA-122167031-1

# Comments
disqus-shortname: davidyujia

exclude:
  - README.md
  - LICENSE.md

# Gems
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
